### PR TITLE
fix color on windows

### LINKED ISSUE #6: Color issue on windows
When I list the hosts with `sshed list`, I get bash colors that powershell does not understand.

```
$ sshed.exe list
[36mtest[0m
```

sshed version: 1.0.3
platform: windows 10
term/shell: powershell 5

### PR DESCRIPTION
**Pull request by fredericrous**
fixes https://github.com/trntv/sshed/issues/6

I included go-colorable which is suggested on github.com/mgutz/ansi page

### CODE REVIEW

**Comment by trntv** [comment]
it will fix problem only in list. Is everything else works ok?

**Comment by fredericrous** [comment]
Let's wait https://github.com/kevinburke/ssh_config/pull/14 is merged and I'll tell you =D

**Comment by trntv** [comment]
ssh_config already updated

**Comment by fredericrous** [comment]
You were right. I get also the problem with red color.
ie: `[31m Error: host not found`

**Comment by fredericrous** [comment]
I'm closing this for now

**Pull request closed without merging**
